### ISSUE TITLE
(Question) Link m17-tools against 3rd party audio without it installed

### ISSUE THREAD

**Issue by alphafox02** [M17-Project/m17-tools#15]
On Linux the directions still have the need for the 3rd party rtaudio to be installed, this could be an issue in the case it's already installed (a different version).

I recall building m17-tools on linux in the past and if I'm not mistaken it was possible to just build, but not install rtaudio. Was it just a matter of manually linking to the rtaudio build files?

Thank you.

**Comment by Paulo-D2000** [comment]
Hi! You're correct! You don't need to install RTAudio, just run make (instead of make install and ldconfig) and it should work! Seems like forgot to change the install steps! Thanks for que question :)

**Comment by Paulo-D2000** [comment]
Should be fixed, check the readme.
